version: '3.7'

services:
  flaggor_web:
    container_name: flaggor_web
    build: .
    ports:
      - published: 8000
        target: 8000
    depends_on:
      - flaggor_db
    networks:
      - default
      - flaggor_network
    restart: unless-stopped

  flaggor_db:
    container_name: flaggor_db
    image: postgres
    environment:
      POSTGRES_DB: flaggor_db
      POSTGRES_USER: flaggor_user
      POSTGRES_PASSWORD: flaggor_password
      POSTGRES_HOST: localhost
    networks:
      - default
      - flaggor_network
    ports:
      - target: 5432
        published: 5432
    restart: unless-stopped

networks:
  flaggor_network:
    name: flaggor_network
volumes:
  postgres_data:
