version: '3.7'

services:
  flaggor_web:
    container_name: flaggor_web
    build: .
    ports:
      - published: 8000
        target: 8000
    depends_on:
      - flaggor_db
    networks:
      - default
      - flaggor_network

  flaggor_db:
    container_name: flaggor_db
    image: postgres
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
      - flaggor_network
    ports:
      - target: 5432
        published: 5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-U",
          "postgres_admin"
        ]
      interval: 5s
      timeout: 1s
      retries: 2
    restart: unless-stopped

networks:
  flaggor_network:
    name: flaggor_network
volumes:
  postgres_data:
