name: Python Format Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r src/dev-requirements.txt

    - name: Check Code Formatting
      run: black --check .

    - name: Fail if Formatting Issues
      run: exit $(black --check .; echo $?)
